# Generated by Django 5.2 on 2025-04-22 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
                ('note', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_resultat', models.DecimalField(decimal_places=4, max_digits=5)),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('Conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.conseil')),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apis.login')),
            ],
        ),
    ]
