# Generated by Django 5.2 on 2025-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_remove_conseil_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
