# Generated by Django 5.2 on 2025-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_alter_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
