# Generated by Django 5.2 on 2025-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_historique_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
